messages:
  - >
    Do NOT store data in your home, use s3://koesterlab/<project>, access with s5cmd
    and by setting --default-storage-prefix s3://koesterlab/<project>
  - Do not compute on the machine main. Instead, jump to compute01.
  - >
    Put any workflows in project specific subfolders under /mnt/workspace/<project>/
    on compute01.
  - >
    Do NOT put non-public human or personal data anywhere in here (also not into the
    s3)!
  - >
    Use rclone copy ikim:... s3:koesterlab/... to transfer data from ikim to the s3
    storage.