[ikim]
type = sftp
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
ssh = ssh c2

[s3]
type = s3
provider = Other
env_auth = true
endpoint = https://openstack.cebitec.uni-bielefeld.de:8080
acl = public-read-write